export default{
    one({commit},obj){
        this.state.elMain='one';  
    },
    two({commit},obj){
        this.state.elMain='two';  
    },
    two_1({commit},obj){
        this.state.elMain='two_1';  
    },
    about({commit},obj){
        this.state.elMain='about';  
    },
    education_1({commit},obj){
        this.state.elMain='education_1';  
    },
    cooperation({commit},obj){
        this.state.elMain='cooperation';  
    },
    two({commit},obj){
        this.state.elMain='two';  
    },
    education_3({commit},obj){
        this.state.elMain='education_3';  
    },
    education_4({commit},obj){
        this.state.elMain='education_4';  
    },
    education_2({commit},obj){
        this.state.elMain='education_2';  
    },
    logOut({commit},obj){
           this.state.app_view='login';
           sessionStorage.clear();
           commit('logOut',obj);
    }
}