export default{
    two(state,obj){
        state.two=obj;
    },
    one(state,obj){
        state.one=obj;
    },
    two_1(state,obj){
        state.two_1=obj;
    },
    about(state,obj){
        state.about=obj;
    },
    education_1(state,obj){
        state.education_1=obj;
    },
    cooperation(state,obj){
        state.cooperation=obj;
    },
    one(state,obj){
        state.one=obj;
    },
    two_1(state,obj){
        state.two_1=obj;
    },
    education_3(state,obj){
        state.education_3=obj;
    },
    education_4(state,obj){
        state.education_4=obj;
    },
    education_2(state,obj){
        state.education_2=obj;
    },
}